resource_group_name: "rg-dbx-architect-lab-uat"
workspace_name: "dbw-dbx-architect-lab-uat"
region: "centralus"
pricing_tier: "premium"
managed_resource_group_name: "rg-dbx-architect-lab-uat-managed"

network:
  no_public_ip: true
  public_network_access_enabled: true
  network_security_group_rules_required: "NoAzureDatabricksRules"

  vnet_name: "vnet-dbx-architect-lab-uat"
  public_subnet_name: "snet-dbx-architect-lab-uat-public"
  private_subnet_name: "snet-dbx-architect-lab-uat-private"
  privatelink_subnet_name: "snet-dbx-architect-lab-uat-privatelink"

  vnet_cidr: [ "10.0.1.0/24" ]
  public_subnet_cidr: [ "10.0.1.0/26" ]
  private_subnet_cidr: [ "10.0.1.64/26" ]
  privatelink_subnet_cidr: [ "10.0.1.128/27" ]

private_endpoints:
  ui_name: "pe-dbx-architect-lab-uat-ui"
  auth_name: "pe-dbx-architect-lab-uat-auth"
  backend_name: "pe-dbx-architect-lab-uat-backend"

private_dns:
  mode: "create"
  name: "privatelink.azuredatabricks.net"
  resource_group_name: "rg-dbx-architect-lab-uat"

identity:
  platform_admin_group_name: "DBX_Architect_Lab_Admin"

tags:
  Environment: "uat"
  Application: "AzureDatabricks"
  Compliance: "HIPAA"
  Owner: "DbxArchitectLab"
